services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    restart: on-failure

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    networks:
      inception:
    env_file:
      - .env
    restart: on-failure


  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env
    restart: on-failure

volumes:
  wp-data:
    driver_opts:
      type: none
      o: bind
      device: /home/yadereve/data/wp-data/
  mariadb-data:
    driver_opts:
      type: none
      o: bind
      device: /home/yadereve/data/mariadb-data/

networks:
  inception:
    driver: bridge
