services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wp-php
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    image: wordpress
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

volumes:
  wp-data:
    driver_opts:
      type: none
      o: bind
      device: /home/yadereve/data/wp-data/
  mariadb-data:
    driver_opts:
      type: none
      o: bind
      device: /home/yadereve/data/mariadb-data/

networks:
  inception_network:
    driver: bridge
