services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - wp-data:/var/www/html
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    networks:
      inception:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      WYSQL_PASSWORD: pqssword
    networks:
      inception:

volumes:
  wp-data:

networks:
      inception:
