services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - wp-data:/var/www/html

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - wp-data:/var/www/html

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      WYSQL_PASSWORD: pqssword

volumes:
  wp-data:
